### ISSUE TITLE
After signing a document the layout of the signed part changes

### ISSUE THREAD

**Issue by jasny** [legalthings/feedback#4]
![image](https://cloud.githubusercontent.com/assets/11313258/7611147/b471fd4c-f982-11e4-9646-de9708ab90dc.png)

![image](https://cloud.githubusercontent.com/assets/11313258/7611178/ee6af30a-f982-11e4-891b-20c1ac35109e.png)

---
Moved from legalthings/zzpmodelcontracten-registration#10
/cc @YoLode @yolode

**Comment by YoLode** [comment]
I think this happens because I've used a tabel to place the two parties. I've just checked this myself and when you go to the edit screen the two parties are close to eachother (like the first screenshot) but when you give a couple of tabs in the edit screen and sign then, it works fine.

**Comment by moesjarraf** [comment]
Yes, @YoLode is correct. This happens because a table is being used. Initially the layout is correct, but after the document has been converted back and forward between doctools and pdftools the layout breaks. With each convert the document loses a bit of its styling (you can see this happening with bullets/lists too).

This is not an easy thing to fix in the backend. A quickfix would be to use spaces/tabs instead of tables for alignment.

**Comment by jasny** [comment]
This is an issue of [DocTools](https://github.com/legalthings/doctools) or [PDFTools](https://github.com/legalthings/pdftools). Can't solve at this moment.

**Comment by Sarfaraaz** [comment]
Should be fixed with the recent changes to DocTools and DMS.
